GET http://localhost:4000/adminApi/users
###
PATCH http://localhost:4000/adminApi/userStatus
###
GET http://localhost:4000/adminApi/user/id
###
DELETE http://localhost:4000/adminApi/url/id
###
GET http://localhost:4000/adminApi/dashboard